# Generated by Django 6.0.1 on 2026-02-25 09:21

import modules.exercise.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id_exercise', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('type', models.CharField(help_text='Type exercise: multiple_choice, sentence_order, matching, fill_blank', max_length=50, validators=[modules.exercise.models.validate_exercise_type])),
                ('difficulty', models.CharField(help_text='Difficulty: easy, medium, hard', max_length=20, validators=[modules.exercise.models.validate_difficulty])),
                ('time_limit', models.IntegerField()),
                ('points', models.IntegerField(default=0)),
                ('question_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_exercises',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExerciseProgress',
            fields=[
                ('id_exercise_progress', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=0)),
                ('attemps', models.IntegerField(default=1)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_exercises_progress',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id_question', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('type', models.CharField(help_text='Type exercise: multiple_choice, sentence_order, matching, fill_blank', max_length=50, validators=[modules.exercise.models.validate_exercise_type])),
                ('correct_answer', models.TextField()),
                ('points', models.IntegerField(default=0)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_questions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionOptions',
            fields=[
                ('id_question_option', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_question_options',
                'managed': False,
            },
        ),
    ]
