# Generated by Django 6.0.1 on 2026-01-31 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserCache',
            fields=[
                ('id_user_cache', models.AutoField(primary_key=True, serialize=False)),
                ('streak', models.IntegerField(default=0)),
                ('id_user', models.IntegerField()),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_user_cache',
                'managed': False,
            },
        ),
    ]
