# Generated by Django 6.0.1 on 2026-01-31 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id_certificate', models.AutoField(primary_key=True, serialize=False)),
                ('name_certificate', models.TextField()),
                ('description_certificate', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_certificate',
                'managed': False,
            },
        ),
    ]
