# Generated by Django 6.0.1 on 2026-01-31 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateCache',
            fields=[
                ('id_certificate_cache', models.AutoField(primary_key=True, serialize=False)),
                ('received_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_certificate_cache',
                'managed': False,
            },
        ),
    ]
