# Generated by Django 6.0.1 on 2026-01-31 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_certificatecache'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNote',
            fields=[
                ('id_note', models.AutoField(primary_key=True, serialize=False)),
                ('content_note', models.TextField()),
                ('description_note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_user_note',
                'managed': False,
            },
        ),
    ]
