# Generated by Django 6.0.1 on 2026-01-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_usernote'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryProgress',
            fields=[
                ('id_history_progress', models.AutoField(primary_key=True, serialize=False)),
                ('isFinished', models.BooleanField(default=False)),
                ('finished_date', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('id_vocabulary_progress', models.IntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_history_progress',
                'managed': False,
            },
        ),
    ]
