# Generated by Django 6.0.1 on 2026-03-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0005_historyprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryLevel',
            fields=[
                ('id_category_level', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.PositiveIntegerField()),
                ('xp_level', models.BigIntegerField()),
                ('condition', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_category_level',
                'managed': False,
            },
        ),
    ]
