# Generated by Django 6.0.1 on 2026-04-08 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0006_categorylevel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorylevel',
            options={'managed': False, 'ordering': ['xp_level']},
        ),
        migrations.AlterModelOptions(
            name='usercache',
            options={'managed': False, 'ordering': ['-gain_xp']},
        ),
    ]
