# Generated by Django 6.0.1 on 2026-05-16 16:52

import django.db.models.deletion
import modules.premium_course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0003_language_mean_vocabulary_alter_topic_options'),
        ('progress', '0007_alter_categorylevel_options_alter_usercache_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseReadingPremium',
            fields=[
                ('id_reading_exercise', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('icon', models.TextField()),
                ('xp_receive', models.IntegerField()),
                ('balance_learn', models.IntegerField()),
                ('type', models.CharField(help_text='Type exercise: multiple_choice, sentence_order, matching, fill_blank, all', max_length=50, validators=[modules.premium_course.models.validate_exercise_type])),
                ('difficulty', models.CharField(help_text='Difficulty: easy, medium, hard', max_length=20, validators=[modules.premium_course.models.validate_difficulty])),
                ('time_limit', models.IntegerField()),
                ('points', models.IntegerField(default=0)),
                ('question_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_exercises_reading_premium',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExerciseProgressPremium',
            fields=[
                ('id_exercise_progress', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=0)),
                ('attempts', models.IntegerField(default=1)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_cache', models.ForeignKey(db_column='id_user_cache', on_delete=django.db.models.deletion.CASCADE, related_name='user_exercise_progress_premium', to='progress.usercache')),
                ('exercises', models.ForeignKey(db_column='id_reading_exercise', on_delete=django.db.models.deletion.CASCADE, related_name='progress_exercise_premium', to='premium_course.exercisereadingpremium')),
            ],
            options={
                'db_table': 'tbl_exercises_progress_reading_premium',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id_reading', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('mean_content', models.TextField()),
                ('img_path', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.ForeignKey(db_column='id_level', on_delete=django.db.models.deletion.CASCADE, related_name='reading_level', to='course.level')),
            ],
            options={
                'db_table': 'tbl_reading',
                'ordering': ['title'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='exercisereadingpremium',
            name='reading',
            field=models.ForeignKey(db_column='id_reading', on_delete=django.db.models.deletion.CASCADE, related_name='exercise_reading', to='premium_course.reading'),
        ),
        migrations.CreateModel(
            name='VocabularyReading',
            fields=[
                ('id_vocabulary_reading', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.TextField()),
                ('meaning', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reading', models.ForeignKey(db_column='id_reading', on_delete=django.db.models.deletion.CASCADE, related_name='reading_vocabulary', to='premium_course.reading')),
                ('user_cache', models.ForeignKey(db_column='id_user_cache', on_delete=django.db.models.deletion.CASCADE, related_name='user_save_vocabulary', to='progress.usercache')),
            ],
            options={
                'db_table': 'tbl_save_reading_vocabulary',
                'ordering': ['word'],
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='reading',
            index=models.Index(fields=['title'], name='idx_title'),
        ),
        migrations.AddConstraint(
            model_name='reading',
            constraint=models.UniqueConstraint(fields=('title',), name='unique_title'),
        ),
        migrations.AddConstraint(
            model_name='vocabularyreading',
            constraint=models.UniqueConstraint(fields=('user_cache', 'word', 'reading'), name='unique_user_word_reading'),
        ),
    ]
