# Generated by Django 6.0.1 on 2026-06-24 06:54

import modules.premium_course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium_course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseListeningPremium',
            fields=[
                ('id_listening_exercise', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('icon', models.TextField()),
                ('xp_receive', models.IntegerField()),
                ('balance_learn', models.IntegerField()),
                ('type', models.CharField(help_text="Type exercise: 'multiple_choice', 'matching_heading', 'matching_information', 'sentence_completion', 'summary_completion', 'table_completion', 'flow_chart_completion', 'matching_features', 'matching_sentence_endings', 'fill_blank', 'all', 'true_false_notgiven'", max_length=50, validators=[modules.premium_course.models.validate_exercise_type])),
                ('difficulty', models.CharField(help_text='Difficulty: easy, medium, hard', max_length=20, validators=[modules.premium_course.models.validate_difficulty])),
                ('time_limit', models.IntegerField()),
                ('points', models.IntegerField(default=0)),
                ('question_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_exercises_listening_premium',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExerciseProgressListeningPremium',
            fields=[
                ('id_exercise_progress_listening', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('attempts', models.IntegerField(default=1)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_exercises_progress_listening_premium',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExerciseProgressReadingPremium',
            fields=[
                ('id_exercise_progress', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('attempts', models.IntegerField(default=1)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_exercises_progress_reading_premium',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id_goal', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('goal_reading', models.IntegerField()),
                ('goal_listening', models.IntegerField()),
                ('goal_writing', models.IntegerField()),
                ('goal_speaking', models.IntegerField()),
                ('goal_xp', models.IntegerField()),
                ('actual_reading', models.IntegerField(default=0)),
                ('actual_listening', models.IntegerField(default=0)),
                ('actual_writing', models.IntegerField(default=0)),
                ('actual_speaking', models.IntegerField(default=0)),
                ('actual_xp', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_goals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Listening',
            fields=[
                ('id_listening', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('audio_path', models.FileField(upload_to='listening/audio/')),
                ('transcript', models.TextField()),
                ('duration', models.IntegerField()),
                ('img_path', models.ImageField(upload_to='listening/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_listening',
                'ordering': ['title'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionGroupListeningPremium',
            fields=[
                ('id_question_listening_premium_group', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('instruction', models.TextField()),
                ('type', models.CharField(max_length=50, validators=[modules.premium_course.models.validate_question_type])),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('order_no', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_question_listening_group_premium',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionGroupPremium',
            fields=[
                ('id_question_premium_group', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('instruction', models.TextField()),
                ('type', models.CharField(max_length=50, validators=[modules.premium_course.models.validate_question_type])),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('order_no', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_question_group_premium',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionListeningPremium',
            fields=[
                ('id_question_listening_premium', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('type', models.CharField(help_text="Type exercise: 'multiple_choice', 'matching_heading', 'matching_information', 'sentence_completion', 'summary_completion', 'table_completion', 'flow_chart_completion', 'matching_features', 'matching_sentence_endings', 'fill_blank', 'true_false_notgiven'", max_length=50, validators=[modules.premium_course.models.validate_question_type])),
                ('words', models.JSONField(blank=True, default=list, help_text="User sort order: (example['element 1', 'element 2',...])", null=True)),
                ('metadata', models.JSONField(blank=True, default=list, help_text='{"pairs":[{ "id": 1, "left": "Dog", "right": "Chó" },{ "id": 2, "left": "Cat", "right": "Mèo" },{ "id": 3, "left": "Bird", "right": "Chim" }]}', null=True)),
                ('correct_answer', models.TextField(null=True)),
                ('points', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('explain_question', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_questions_listening_premium',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionOptionsListeningPremium',
            fields=[
                ('id_question_listening_premium_option', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_question_listening_premium_options',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionOptionsPremium',
            fields=[
                ('id_question_premium_option', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_question_premium_options',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionPremium',
            fields=[
                ('id_question_premium', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('type', models.CharField(help_text="Type exercise: 'multiple_choice', 'matching_heading', 'matching_information', 'sentence_completion', 'summary_completion', 'table_completion', 'flow_chart_completion', 'matching_features', 'matching_sentence_endings', 'fill_blank', 'true_false_notgiven'", max_length=50, validators=[modules.premium_course.models.validate_question_type])),
                ('words', models.JSONField(blank=True, default=list, help_text="User sort order: (example['element 1', 'element 2',...])", null=True)),
                ('metadata', models.JSONField(blank=True, default=list, help_text='{"pairs":[{ "id": 1, "left": "Dog", "right": "Chó" },{ "id": 2, "left": "Cat", "right": "Mèo" },{ "id": 3, "left": "Bird", "right": "Chim" }]}', null=True)),
                ('correct_answer', models.TextField(null=True)),
                ('points', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('explain_question', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_questions_premium',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SaveVocabularyReading',
            fields=[
                ('id_vocabulary_reading', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.TextField()),
                ('meaning', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_save_reading_vocabulary',
                'ordering': ['word'],
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='exerciseprogresspremium',
            name='exercises',
        ),
        migrations.RemoveField(
            model_name='exerciseprogresspremium',
            name='user_cache',
        ),
        migrations.RemoveConstraint(
            model_name='vocabularyreading',
            name='unique_user_word_reading',
        ),
        migrations.AlterModelOptions(
            name='exercisereadingpremium',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='reading',
            options={'managed': False, 'ordering': ['title']},
        ),
        migrations.DeleteModel(
            name='ExerciseProgressPremium',
        ),
        migrations.DeleteModel(
            name='VocabularyReading',
        ),
    ]
