# Generated by Django 6.0.1 on 2026-01-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id_topic', models.AutoField(primary_key=True, serialize=False)),
                ('name_topic', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_topic',
                'ordering': ['name_topic'],
                'indexes': [models.Index(fields=['name_topic'], name='idx_name_topic')],
                'constraints': [models.UniqueConstraint(fields=('name_topic',), name='unique_name_topic')],
            },
        ),
    ]
