# Generated by Django 6.0.1 on 2026-03-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id_language', models.AutoField(primary_key=True, serialize=False)),
                ('language_code', models.CharField(max_length=10)),
                ('name_language', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbl_language',
                'ordering': ['language_code'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mean',
            fields=[
                ('id_mean', models.AutoField(primary_key=True, serialize=False)),
                ('mean_vocabulary', models.CharField(max_length=255)),
                ('example_vocabulary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbl_mean',
                'ordering': ['mean_vocabulary'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id_vocabulary', models.AutoField(primary_key=True, serialize=False)),
                ('name_vocabulary', models.CharField(max_length=255)),
                ('ipa', models.CharField(max_length=255)),
                ('img_path', models.ImageField(blank=True, null=True, upload_to='vocabulary/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_vocabulary',
                'ordering': ['name_vocabulary'],
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'managed': False, 'ordering': ['name_topic']},
        ),
    ]
